# Swift Subset Syntax Validator

This project implements a **Lexer** and **Parser** for a subset of the **Swift** programming language using the **Python Lex-Yacc (PLY)** library. It is designed to validate the syntax of key Swift constructs, demonstrating fundamental concepts of formal language theory and compiler construction.

## 🚀 Features

The validator is capable of performing lexical and syntactic analysis for the following Swift language features:

- **Variables and Constants:** `let` and `var` declarations, with optional type annotation and initialization.

- **Structures (****`struct`****):** Declaration of custom data types.

- **Generics:** Support for type parameter lists (`<T: Constraint, U>`) in structures.

- **Protocols:** Minimal support for protocol declarations.

- **Error Handling:** Detects and reports both lexical and syntactic errors.

## 🛠️ Installation and Setup

### Prerequisites

- Python 3.x

- The `ply` library

### Setup

1. **Clone the repository** (or download the files).

1. **Install the PLY library:**

## 💡 Usage

The validator runs as a command-line application, allowing you to input Swift code directly for validation.

1. **Run the main script:**

1. **Enter your Swift code:**

1. **Exit:**

## 📂 Project Structure

The core components of the validator are organized as follows:

| File | Description |
| --- | --- |
| `main.py` | The entry point of the application. Handles user input and orchestrates the validation process using the lexer and parser. |
| `lexer.py` | Contains the **Lexical Analyzer** (Lexer) definitions using `ply.lex`. Defines tokens, regular expressions, and handles lexical errors. |
| `parser.py` | Contains the **Syntactic Analyzer** (Parser) definitions using `ply.yacc`. Implements the Context-Free Grammar (CFG) rules for the Swift subset. |
| `swift.swift` | A sample file containing valid and invalid Swift code examples for testing and demonstration. |
| `parser.out` | Output file generated by PLY containing the parsing table. |
|  |

## 📝 Grammar Overview

The parser is built upon a Context-Free Grammar (CFG) that defines the valid structure of the Swift subset.

### Key Grammar Rules

The grammar covers the structure of declarations, including:

- **Variable/Constant Declaration:** `var_declaration : LET/VAR ID type_annotation assignment`

- **Structure Declaration:** `struct_declaration : STRUCT ID generic_params where_clause_opt LBRACE property_declaration_list RBRACE`

- **Generic Parameters:** `generic_params : LT generic_parameter_list RANGLE`

- **Type Constraint:** `constraint : ID COLON ID` (e.g., `T: Hashable`)

---

*This README was generated to help you document your project for GitHub.*

